export const RESTORED_PUBLIC_OPPORTUNITIES: any[] = [
  {
    id: "restored-cabin-crew-international-routes",
    title: "Cabin Crew — International Routes",
    slug: "cabin-crew-international-routes",
    location: "Dubai International Airport",
    country: "United Arab Emirates",
    city: "Dubai",
    employment_type: "Full-time",
    duration: "2 year contract",
    salary: "2,500 - 3,200",
    currency: "USD",
    deadline: "2026-11-11",
    published_at: "2026-09-27T00:00:00.000Z",
    featured: true,
    urgent: false,
    verified: true,
    status: "published",
    category: { name: "Air Hostess / Cabin Crew", slug: "air-hostess" },
    company: { name: "Horizon Air Services", slug: "horizon-air-services", verified: true },
    images: [],
  },
  {
    id: "restored-live-in-caregiver",
    title: "Live-in Caregiver",
    slug: "live-in-caregiver",
    location: "Manchester",
    country: "United Kingdom",
    city: "Manchester",
    employment_type: "Full-time",
    duration: "12 months",
    salary: "1,900 - 2,300",
    currency: "GBP",
    deadline: "2026-10-27",
    published_at: "2026-09-27T00:00:00.000Z",
    featured: true,
    urgent: true,
    verified: true,
    status: "published",
    category: { name: "Caregivers", slug: "caregivers" },
    company: { name: "CarePlus Group", slug: "careplus-group", verified: true },
    images: [],
  },
];
