export const RESTORED_PUBLIC_OPPORTUNITIES: any[] = [
  {
    id: "restored-cabin-crew-international-routes", title: "Cabin Crew — International Routes", slug: "cabin-crew-international-routes",
    location: "Dubai International Airport", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "2 year contract", salary: "2,500 - 3,200", currency: "USD", vacancies: 12, deadline: "2026-11-11",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Air Hostess / Cabin Crew", slug: "air-hostess" },
    company: { name: "Horizon Air Services", slug: "horizon-air-services", verified: true }, images: [],
  },
  {
    id: "restored-live-in-caregiver", title: "Live-in Caregiver", slug: "live-in-caregiver",
    location: "Manchester", country: "United Kingdom", city: "Manchester", employment_type: "Full-time",
    duration: "12 months", salary: "1,900 - 2,300", currency: "GBP", vacancies: 6, deadline: "2026-10-27",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: true, verified: true, status: "published",
    category: { name: "Caregivers", slug: "caregivers" },
    company: { name: "CarePlus Group", slug: "careplus-group", verified: true }, images: [],
  },
  {
    id: "restored-emirates-cabin-crew", title: "Cabin Crew Opportunities", slug: "northstar-emirates-cabin-crew",
    location: "Dubai International Airport", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Long-term", salary: "AED 4,980 basic + AED 69.60 flying pay/hour; average monthly pay about AED 11,244", currency: "AED",
    vacancies: 20, deadline: "2026-12-31", published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Aviation", slug: "aviation" }, company: { name: "Emirates Group", slug: "emirates-group", verified: true }, images: [],
  },
  {
    id: "restored-emirates-cabin-services", title: "Cabin Services Assistant", slug: "northstar-emirates-cabin-services-assistant",
    location: "Dubai", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Long-term", salary: "AED 4,500-6,500", currency: "AED", vacancies: 10, deadline: "2026-12-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Aviation", slug: "aviation" }, company: { name: "Emirates Group", slug: "emirates-group", verified: true }, images: [],
  },
  {
    id: "restored-emirates-engineering", title: "Engineering Projects Officer", slug: "northstar-emirates-engineering-projects-officer",
    location: "Dubai", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Long-term", salary: "AED 12,000-20,000", currency: "AED", vacancies: 3, deadline: "2026-12-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Engineering", slug: "engineering" }, company: { name: "Emirates Group", slug: "emirates-group", verified: true }, images: [],
  },
  {
    id: "restored-emirates-security", title: "Security Coordinator - Passport & Visa Verification", slug: "northstar-emirates-security-coordinator",
    location: "Dubai", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Long-term", salary: "AED 7,000-11,000", currency: "AED", vacancies: 4, deadline: "2026-12-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Security", slug: "security" }, company: { name: "Emirates Group", slug: "emirates-group", verified: true }, images: [],
  },
  {
    id: "restored-etihad-cabin-crew", title: "Cabin Crew", slug: "northstar-etihad-cabin-crew",
    location: "Abu Dhabi", country: "United Arab Emirates", city: "Abu Dhabi", employment_type: "Full-time",
    duration: "Three-year renewable contract", salary: "Competitive tax-free salary and travel package", currency: "AED", vacancies: 20, deadline: "2026-12-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Aviation", slug: "aviation" }, company: { name: "Etihad Airways", slug: "etihad-airways", verified: true }, images: [],
  },
  {
    id: "restored-amazon-fulfilment", title: "Fulfilment Associate", slug: "northstar-amazon-fulfilment-associate",
    location: "Poznan / Sady", country: "Poland", city: "Poznan", employment_type: "Full-time",
    duration: "Long-term", salary: "37.50", currency: "PLN/hour", vacancies: 20, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Warehouse", slug: "warehouse" }, company: { name: "Amazon Poland", slug: "amazon-poland", verified: true }, images: [],
  },
  {
    id: "restored-amazon-inbound", title: "External Fulfillment CT Inbound Specialist", slug: "northstar-amazon-inbound-specialist",
    location: "Poznan / Gliwice / Bielany Wroclawskie", country: "Poland", city: "Poznan", employment_type: "Full-time",
    duration: "Long-term", salary: "37.50", currency: "PLN/hour", vacancies: 2, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Warehouse", slug: "warehouse" }, company: { name: "Amazon Poland", slug: "amazon-poland", verified: true }, images: [],
  },
  {
    id: "restored-dhl-warehouse", title: "Warehouse Operative", slug: "northstar-dhl-warehouse-operative",
    location: "Warsaw", country: "Poland", city: "Warsaw", employment_type: "Full-time",
    duration: "Long-term", salary: "PLN 5,500-7,500", currency: "PLN/month", vacancies: 8, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Warehouse", slug: "warehouse" }, company: { name: "DHL Supply Chain Poland", slug: "dhl-supply-chain-poland", verified: true }, images: [],
  },
  {
    id: "restored-marriott-cleanliness", title: "Hotel Cleanliness Expert", slug: "northstar-marriott-hotel-cleanliness-expert",
    location: "Sheraton Mall of the Emirates Hotel", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Long-term", salary: "AED 2,500-3,500", currency: "AED/month", vacancies: 5, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Housekeeping", slug: "housekeeping" }, company: { name: "Marriott International", slug: "marriott-international", verified: true }, images: [],
  },
  {
    id: "restored-marriott-banquet", title: "Banquet Intern", slug: "northstar-marriott-banquet-intern-dubai",
    location: "JW Marriott Marquis Hotel Dubai", country: "United Arab Emirates", city: "Dubai", employment_type: "Full-time",
    duration: "Internship", salary: "AED 2,000-3,000", currency: "AED/month", vacancies: 3, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Hospitality", slug: "hospitality" }, company: { name: "Marriott International", slug: "marriott-international", verified: true }, images: [],
  },
  {
    id: "restored-g4s-security", title: "Security Officer", slug: "northstar-g4s-security-officer",
    location: "Riyadh", country: "Saudi Arabia", city: "Riyadh", employment_type: "Full-time",
    duration: "Long-term", salary: "SAR 3,500-5,000", currency: "SAR/month", vacancies: 8, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Security", slug: "security" }, company: { name: "G4S", slug: "g4s", verified: true }, images: [],
  },
  {
    id: "restored-pcl-project", title: "Project Coordinator", slug: "northstar-pcl-project-coordinator-fort-mcmurray",
    location: "Fort McMurray, Alberta", country: "Canada", city: "Fort McMurray", employment_type: "Full-time",
    duration: "Contract / project-based", salary: "CAD 69,800-104,600", currency: "CAD/year", vacancies: 1, deadline: "2026-11-30",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Construction", slug: "construction" }, company: { name: "PCL Construction", slug: "pcl-construction", verified: true }, images: [],
  },
  {
    id: "restored-aramco-engineer", title: "Experienced Engineer", slug: "northstar-aramco-experienced-engineer",
    location: "Dhahran / Saudi Arabia", country: "Saudi Arabia", city: "Dhahran", employment_type: "Full-time",
    duration: "Long-term", salary: "SAR 18,000-30,000", currency: "SAR/month", vacancies: 5, deadline: "2026-12-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Engineering", slug: "engineering" }, company: { name: "Saudi Aramco", slug: "saudi-aramco", verified: true }, images: [],
  },
  {
    id: "restored-barchester-care", title: "Care Assistant", slug: "northstar-barchester-care-assistant-manchester",
    location: "Manchester", country: "United Kingdom", city: "Manchester", employment_type: "Full-time",
    duration: "Permanent", salary: "GBP 12.50-14.50", currency: "GBP/hour", vacancies: 6, deadline: "2026-10-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: false, urgent: false, verified: true, status: "published",
    category: { name: "Caregiving", slug: "caregiving" }, company: { name: "Barchester Healthcare", slug: "barchester-healthcare", verified: true }, images: [],
  },
  {
    id: "restored-stagecoach-driver", title: "Bus Driver", slug: "northstar-stagecoach-bus-driver-manchester",
    location: "Manchester", country: "United Kingdom", city: "Manchester", employment_type: "Full-time",
    duration: "Permanent", salary: "GBP 19.06/hour; GBP 21.31 Saturday & Sunday + overtime", currency: "GBP/hour", vacancies: 8, deadline: "2026-10-31",
    published_at: "2026-09-27T00:00:00.000Z", featured: true, urgent: false, verified: true, status: "published",
    category: { name: "Driving", slug: "driving" }, company: { name: "Stagecoach", slug: "stagecoach", verified: true }, images: [],
  },
] as const;
