/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesSlugRouteImport } from './routes/opportunities.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalApplyRouteImport } from './routes/_authenticated/portal.apply'
import { Route as AuthenticatedAdminApplicationsIndexRouteImport } from './routes/_authenticated/admin.applications.index'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin.applications.$id'
import { Route as AuthenticatedAdminOpportunitiesIndexRouteImport } from './routes/_authenticated/admin.opportunities.index'
import { Route as AuthenticatedAdminOpportunitiesIdRouteImport } from './routes/_authenticated/admin.opportunities.$id'
import { Route as AuthenticatedPortalApplicationsIdRouteImport } from './routes/_authenticated/portal.applications.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesSlugRoute = OpportunitiesSlugRouteImport.update({
  id: '/opportunities/$slug',
  path: '/opportunities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalApplyRoute =
  AuthenticatedPortalApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminApplicationsIndexRoute =
  AuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesIndexRoute =
  AuthenticatedAdminOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesIdRoute =
  AuthenticatedAdminOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalApplicationsIdRoute =
  AuthenticatedPortalApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/portal/apply': typeof AuthenticatedPortalApplyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/companies': typeof CompaniesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/portal/apply': typeof AuthenticatedPortalApplyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsIndexRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/portal/apply': typeof AuthenticatedPortalApplyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/_authenticated/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/_authenticated/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/_authenticated/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
  '/_authenticated/admin/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/portal'
    | '/category/$slug'
    | '/companies/$slug'
    | '/opportunities/$slug'
    | '/companies/'
    | '/opportunities/'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/enquiries'
    | '/admin/settings'
    | '/portal/apply'
    | '/admin/'
    | '/portal/'
    | '/admin/applications/$id'
    | '/admin/opportunities/$id'
    | '/portal/applications/$id'
    | '/api/public/media/$'
    | '/admin/applications/'
    | '/admin/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/category/$slug'
    | '/companies/$slug'
    | '/opportunities/$slug'
    | '/companies'
    | '/opportunities'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/enquiries'
    | '/admin/settings'
    | '/portal/apply'
    | '/admin'
    | '/portal'
    | '/admin/applications/$id'
    | '/admin/opportunities/$id'
    | '/portal/applications/$id'
    | '/api/public/media/$'
    | '/admin/applications'
    | '/admin/opportunities'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/apply'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/category/$slug'
    | '/companies/$slug'
    | '/opportunities/$slug'
    | '/companies/'
    | '/opportunities/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/settings'
    | '/_authenticated/portal/apply'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/applications/$id'
    | '/_authenticated/admin/opportunities/$id'
    | '/_authenticated/portal/applications/$id'
    | '/api/public/media/$'
    | '/_authenticated/admin/applications/'
    | '/_authenticated/admin/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  OpportunitiesSlugRoute: typeof OpportunitiesSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$slug': {
      id: '/opportunities/$slug'
      path: '/opportunities/$slug'
      fullPath: '/opportunities/$slug'
      preLoaderRoute: typeof OpportunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/apply': {
      id: '/_authenticated/portal/apply'
      path: '/apply'
      fullPath: '/portal/apply'
      preLoaderRoute: typeof AuthenticatedPortalApplyRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/applications/': {
      id: '/_authenticated/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/opportunities/': {
      id: '/_authenticated/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/opportunities/$id': {
      id: '/_authenticated/admin/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/admin/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/applications/$id': {
      id: '/_authenticated/portal/applications/$id'
      path: '/applications/$id'
      fullPath: '/portal/applications/$id'
      preLoaderRoute: typeof AuthenticatedPortalApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
  AuthenticatedAdminOpportunitiesIdRoute: typeof AuthenticatedAdminOpportunitiesIdRoute
  AuthenticatedAdminApplicationsIndexRoute: typeof AuthenticatedAdminApplicationsIndexRoute
  AuthenticatedAdminOpportunitiesIndexRoute: typeof AuthenticatedAdminOpportunitiesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApplicationsIdRoute: AuthenticatedAdminApplicationsIdRoute,
  AuthenticatedAdminOpportunitiesIdRoute:
    AuthenticatedAdminOpportunitiesIdRoute,
  AuthenticatedAdminApplicationsIndexRoute:
    AuthenticatedAdminApplicationsIndexRoute,
  AuthenticatedAdminOpportunitiesIndexRoute:
    AuthenticatedAdminOpportunitiesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalApplyRoute: typeof AuthenticatedPortalApplyRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalApplicationsIdRoute: typeof AuthenticatedPortalApplicationsIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalApplyRoute: AuthenticatedPortalApplyRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalApplicationsIdRoute:
    AuthenticatedPortalApplicationsIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  OpportunitiesSlugRoute: OpportunitiesSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
